Dco
BonnyCI/hoist pull request #10
Opened 2016-12-16 21:09 UTC by nibalizer

2016-12-16 21:41 UTC, egg-shell commented on README.rst
> +See CONTRIBUTING.md in this repository
Any reason not to include a relative link?

2016-12-16 21:42 UTC, eggshell approved these changes
Other than the nit about the contribution link, lgtm.

2016-12-16 23:54 UTC, nibalizer commented on test/signed-off-by-test.sh
> +    if $(git show $commit | grep -q Signed-off-by ); then
if we add -s to git show here, it wont emit the diff, which removes a bug where 'signed-off-by' can be in the diff.

2016-12-17 00:34 UTC, j2sol commented
recheck

2016-12-17 00:34 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2016-12-17 00:48 UTC, ConsoleCatzirl requested changes

2016-12-17 00:48 UTC, jesusaurus commented on CONTRIBUTING.md
> +You can do this easily in git but using ``-s`` when you run ``git commit``
Typo: s/but/by/

2016-12-17 00:48 UTC, jesusaurus commented on README.rst
> +See CONTRIBUTING.md in this repository
Yeah, a relative link would be good

2016-12-17 00:48 UTC, jesusaurus commented on test/signed-off-by-test.sh
> +        :
Why not negate the if instead of having an empty section here?

2016-12-17 01:01 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2016-12-17 01:02 UTC, j2sol commented
recheck

2016-12-17 01:02 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2016-12-17 01:04 UTC, j2sol commented
recheck

2016-12-17 01:04 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2016-12-17 01:07 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2016-12-17 01:14 UTC, ConsoleCatzirl approved these changes

2016-12-17 01:28 UTC, merged