Update hoist tests to use in-repo run.sh
BonnyCI/hoist pull request #103
Opened 2017-02-03 18:30 UTC by gandelman-a

2017-02-03 18:34 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486146609.58/ubuntu-hoist : SUCCESS in 4m 19s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486146609.58/ansible-syntax : SUCCESS in 57s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486146609.58/hoist-checks : FAILURE in 12s

2017-02-03 18:40 UTC, j2sol commented
This looks like it'll take our 3 jobs which could be ran in parallel and instead makes it a single serial job?

Where in this new setup is the node label defined, since at least one of these jobs needs the `ubuntu-hoist` node set.

2017-02-03 19:28 UTC, gandelman-a commented on tests/test-hoist-ansible.sh
> +ansible-playbook -i /dev/null --syntax-check $(find . tests -maxdepth 1 -type f -name \*.yml -not -name .travis.yml)
shellchecks SC2046 prohibits this and requires the $() to be quoted, which borks this call as it passes in the entire find result as a single parameter.  Disabled that check below.

2017-02-03 19:34 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486150139.44/ubuntu-hoist : SUCCESS in 4m 16s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486150139.44/ansible-syntax : SUCCESS in 54s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486150139.44/hoist-checks : FAILURE in 11s

2017-02-03 19:46 UTC, ConsoleCatzirl requested changes
For the most part this is looking good

2017-02-03 19:46 UTC, jesusaurus commented on .bonnyci/run.sh
> +    ansible-galaxy install -r install -r requirements.txt
This should be `requirements.yml` instead of `requirements.txt`

2017-02-03 19:46 UTC, jesusaurus commented on roles/zuul/files/jobs/bonnyci.yaml
> +    node: 'ubuntu-xenial'
Does this work as a default value? I think that this needs to be `node: {node}` in order to use the parameter passed below.

2017-02-03 19:48 UTC, gandelman-a commented on .bonnyci/run.sh
> +    ansible-galaxy install -r install -r requirements.txt
doh

2017-02-03 19:49 UTC, gandelman-a commented on roles/zuul/files/jobs/bonnyci.yaml
> +    node: 'ubuntu-xenial'
Yeah, this is just the default value.  Passing a node in below will overwrite it.  Verified this locally by referencing it in the executor and inspecting the generated job.

2017-02-03 19:55 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486151460.26/ubuntu-hoist : SUCCESS in 4m 14s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486151460.26/ansible-syntax : SUCCESS in 55s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486151460.26/hoist-checks : FAILURE in 12s

2017-02-03 20:13 UTC, ConsoleCatzirl approved these changes
LGTM

2017-02-03 20:13 UTC, jesusaurus commented on roles/zuul/files/jobs/bonnyci.yaml
> +    node: 'ubuntu-xenial'
cool

2017-02-06 23:46 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486424478.52/ubuntu-hoist : SUCCESS in 4m 52s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486424478.52/ansible-syntax : SUCCESS in 55s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/103/1486424478.52/hoist-checks : FAILURE in 11s

2017-02-09 17:49 UTC, ConsoleCatzirl approved these changes

2017-02-13 19:33 UTC, j2sol commented
I'm assuming bonny is not merging this because there are historical negative reviews. Is that right?

2017-02-13 19:37 UTC, j2sol commented
gate-recheck

2017-02-13 19:45 UTC, merged