Runner test
BonnyCI/hoist pull request #215
Opened 2017-03-10 20:54 UTC by gandelman-a

2017-03-10 20:55 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/215/1489179290.32/bonnyci-run-check-multinode : FAILURE in 57s

2017-03-10 20:57 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/215/1489179358.82/bonnyci-run-check-multinode : FAILURE in 56s

2017-03-10 21:38 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/215/1489181900.4/bonnyci-run-check-multinode : FAILURE in 20s

2017-03-10 22:21 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/215/1489184201.44/bonnyci-run-check-multinode : FAILURE in 20s

2017-03-10 22:42 UTC, anne-bonny commented
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

2017-03-10 22:53 UTC, ConsoleCatzirl requested changes
There's a typo that needs to be fixed. But also, why does this need the overhead of a git repo? What do we gain by committing test files into a throwaway repo?

2017-03-10 22:53 UTC, jesusaurus commented on roles/ansible-runner/files/usr/local/bin/ansible-runner
> +if [ -f /etc/default/env ]; then
Typo: `/etc/default/env` should be `/etc/default/$env`

2017-03-13 17:43 UTC, gandelman-a commented
So one of the core functions of the script is to pull down new revisions into a local checkout and apply those new ansible and requirement changes.  Our test should validate that this actually works. IIRC there were some instances where we were running ansible on outdated repos. 

Also, we require a git checkout for the script to even run.

2017-03-13 17:43 UTC, gandelman-a commented on roles/ansible-runner/files/usr/local/bin/ansible-runner
> +if [ -f /etc/default/env ]; then
Doh

2017-03-13 17:46 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/215/1489427120.68/bonnyci-run-check-multinode : FAILURE in 1m 03s

2017-03-13 18:11 UTC, gandelman-a commented
recheck

2017-03-13 18:50 UTC, omgjlk approved these changes
Looks good. Yay for more coverage.

2017-03-14 01:01 UTC, ConsoleCatzirl approved these changes

2017-03-14 20:55 UTC, jesusaurus commented
gate-recheck

2017-03-14 22:47 UTC, merged