separate datadog-builder from bastion role
BonnyCI/hoist pull request #276
Opened 2017-03-29 14:47 UTC by loafyloaf

Signed-off-by: matthew wagoner <zxkuqyb@gmail.com>

2017-04-03 18:40 UTC, gandelman-a commented
Without a commit msg its kinda hard to determine the intent of this?  Its just moving the datadog-builder role off of the bastion into its own group, but results in that stuff not running anymore.

2017-04-03 18:40 UTC, gandelman-a requested changes

2017-04-03 18:40 UTC, gandelman-a commented on dd-builder.yml
> +            - notifempty
So as-is, nothing is setup to actually run this playbook in the same way we  do bastion.yml or install-ci.yml.  Was this intentional?

2017-04-06 16:40 UTC, loafyloaf commented
so, at the time, datadog-builder was running on two bastions - contrasjc and opentechsjc.  While this shouldn't really be a problem, the monitors.yml file was not getting updated on contrasjc, so when 'new' bastion created a monitor, 'old' bastion would delete it.  This is a bit moot now, seeing as how contrasjc is gone.  But perhaps we may get a second cloud in the future...

2017-04-06 21:29 UTC, jesusaurus commented on dd-builder.yml
> +            - notifempty
Is the idea to create a new ansible-runner cron for this playbook?

2017-04-11 21:24 UTC, mlangbehn commented
Per discussion with @loafyloaf in IRC, this pull request is no longer needed. Closing accordingly.

2017-04-11 21:24 UTC, closed without merging