Use become_user instead of ansible_user in validate script
BonnyCI/hoist pull request #52
Opened 2017-01-10 22:59 UTC by jamielennox

By setting the ansible_user=nodepool you tell ansible to try and ssh
into the nodepool machine as the nodepool user. What we want is to
continue to ssh as the bonnyci user, but sudo to being the nodepool user
once on the machine. This is done via become.

Signed-off-by: Jamie Lennox <jamielennox@gmail.com>

2017-01-10 23:00 UTC, omgjlk approved these changes
Solid reasoning.

2017-01-10 23:01 UTC, ConsoleCatzirl approved these changes

2017-01-10 23:57 UTC, j2sol commented on tests/validate-ci.yml
> -        - ansible_user: nodepool
Maybe try changing this to `ansible_become: true` and leave the rest as you have it?

2017-01-11 18:55 UTC, omgjlk requested changes
Depends on #53 , and also changing our docker calls in travis.yaml to not explicitly disable become.

2017-01-11 22:35 UTC, omgjlk approved these changes

2017-01-11 22:35 UTC, anne-bonny commented
Starting gate_github jobs.

2017-01-11 22:35 UTC, merged