Add zuul status page
BonnyCI/hoist pull request #61
Opened 2017-01-17 21:51 UTC by jesusaurus

Add an apache document root pointing at the status page that ships with the zuul source.

2017-01-17 21:53 UTC, jesusaurus commented
This is working in my vagrant environment, but we should hold off on merging before the demo since this could possibly break cloning from the zuul-merger.

2017-01-17 21:55 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484689910.59/ubuntu-hoist : FAILURE in 2m 53s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484689910.59/ansible-syntax : SUCCESS in 52s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484689910.59/hoist-checks : SUCCESS in 7s

2017-01-18 20:43 UTC, jesusaurus commented
Implements BonnyCI/projman#52

2017-01-19 18:13 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484849258.3/ubuntu-hoist : FAILURE in 4m 21s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484849258.3/ansible-syntax : SUCCESS in 54s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484849258.3/hoist-checks : SUCCESS in 7s

2017-01-19 21:17 UTC, jesusaurus commented
recheck

2017-01-19 21:22 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484860623.13/ubuntu-hoist : FAILURE in 4m 15s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484860623.13/ansible-syntax : SUCCESS in 56s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1484860623.13/hoist-checks : SUCCESS in 7s

2017-01-23 00:39 UTC, jamielennox requested changes
Maybe seeing how we are just proxying onto the existing service does it make sense to make zuul-status its own role?

2017-01-23 00:39 UTC, jamielennox commented on roles/zuul/tasks/main.yml
> +    state: directory
This feels wrong, we are creating and adding directories to a git repository. IMO all these files should probably go to /var/www or something and patch it up from apache.

2017-01-23 19:23 UTC, jesusaurus commented on roles/zuul/tasks/main.yml
> +    state: directory
I agree that this is a bit ugly/hacky, but if it makes you feel any better infra does basically the same thing and the public_html/lib directory is in a .gitignore file.

2017-02-01 20:17 UTC, jesusaurus commented on inventory/group_vars/zuul
> +
Yeah, that would probably be best.

2017-02-02 03:42 UTC, jesusaurus commented on inventory/group_vars/zuul
> +
I've created BonnyCI/projman#99 to address moving the merger to a dedicated host.

2017-02-06 23:23 UTC, jamielennox commented on inventory/group_vars/zuul
> +
nit, i'd like to see 8001 refered to on the status page config somewhere as well

2017-02-06 23:23 UTC, jamielennox commented on roles/zuul/tasks/main.yml
> +  when: jquery_graphite|changed
jquery graphite is a one file app, can we do the same thing here as visibility and just download https://raw.githubusercontent.com/prestontimmons/graphitejs/master/jquery.graphite.js

2017-02-06 23:23 UTC, jamielennox commented on roles/zuul/tasks/main.yml
> +  when: bootstrap|changed
https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css

2017-02-07 00:10 UTC, anne-bonny commented
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1486426165.85/ubuntu-hoist : FAILURE in 35s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1486426165.85/ansible-syntax : SUCCESS in 14s
- http://logs.bonnyci.com/check_github/BonnyCI/hoist/61/1486426165.85/hoist-checks : SUCCESS in 20s

2017-02-07 00:18 UTC, jamielennox commented on install-ci.yml
> +      apache_vhosts: "{{ bonnyci_zuul_apache_vhosts }}"
maybe bonnyci_zuul_status_apache_X?

2017-02-07 00:18 UTC, jamielennox commented on inventory/group_vars/vagrant
> +bonnyci_zuul_apache_server_name: zuul.vagrant
bonnyci_zuul_status?

2017-02-07 00:18 UTC, jamielennox commented on roles/zuul/tasks/server.yml
> +    - http://code.jquery.com/jquery.min.js
https

2017-02-07 00:18 UTC, jamielennox commented on roles/zuul/tasks/server.yml
> +    path: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css
bah, stupid zuul, why does this one have to be in a folder.

2017-02-07 00:18 UTC, jamielennox commented on roles/zuul/tasks/server.yml
> +    path: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css
you can combine this with the create folder above

2017-02-07 00:22 UTC, jesusaurus commented on roles/zuul/tasks/server.yml
> +    path: /opt/source/zuul/etc/status/public_html/lib/bootstrap/css
I'm gonna blame bootstrap for this one, since this directory structure seems to come from the zip file we had unzipped in the previous iteration.

2017-02-07 04:36 UTC, jamielennox approved these changes
Sorry it took so long to get here.

2017-02-09 04:32 UTC, j2sol commented on tests/validate-ci.yml
> +      shell: curl --fail localhost:8001/status.json
We can do this with the `uri` module, avoiding the need for the curl install.

2017-02-09 04:33 UTC, omgjlk approved these changes
Looks fine by me. There is a small enhancement that can be done as a follow up commit.

2017-02-09 04:37 UTC, j2sol commented
gate-recheck

2017-02-09 05:16 UTC, merged